name: Compile & Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: make cmake_prod

      - name: Build
        run: make build_prod

      - name: Remove useless files
        run: cd ${{github.workspace}}/cmake-build-release ; rm -rf CMakeFiles Testing

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: linux-amd64-build
          path: ${{github.workspace}}/cmake-build-release

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: make cmake_prod

      - name: Build
        run: make build_prod

      - name: Remove useless files
        run: dir ${{github.workspace}}/cmake-build-release | where {$_. name -notlike '*.exe*'} | Remove-Item -Recurse -force

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows-amd64-build
          path: ${{github.workspace}}/cmake-build-release

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: make cmake_prod

      - name: Build
        run: make build_prod

      - name: Remove useless files
        run: cd ${{github.workspace}}/cmake-build-release ; rm -rf CMakeFiles Testing

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macos-amd64-build
          path: ${{github.workspace}}/cmake-build-release

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: doxygen/html
          config_file: Doxyfile